"""add transaction id and transaction table

Revision ID: 0b9fd71cadfa
Revises: df5e1453777b
Create Date: 2026-09-10 13:46:06.502100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9fd71cadfa'
down_revision: Union[str, Sequence[str], None] = 'df5e1453777b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_link_id', sa.String(length=100), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('razorpay_status', sa.String(length=50), nullable=True),
    sa.Column('refund_status', sa.String(length=50), nullable=True),
    sa.Column('refund_id', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_payment_id'), 'transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_link_id'), 'transactions', ['payment_link_id'], unique=False)
    op.add_column('orders', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'transactions', ['transaction_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'transaction_id')
    op.drop_index(op.f('ix_transactions_payment_link_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
