"""add img_path column in product table

Revision ID: 5b9ab255271c
Revises: 2935c525133d
Create Date: 2026-09-08 15:17:43.609352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9ab255271c'
down_revision: Union[str, Sequence[str], None] = '2935c525133d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img_path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img_path')
    # ### end Alembic commands ###
