"""add transaction id from order table

Revision ID: 6ba76683d19c
Revises: 0b9fd71cadfa
Create Date: 2026-09-10 14:39:02.411682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba76683d19c'
down_revision: Union[str, Sequence[str], None] = '0b9fd71cadfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_transaction_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'transaction_id')
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('transactions', 'refund_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'refund_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('orders', sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_transaction_id_fkey'), 'orders', 'transactions', ['transaction_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
