"""add user_id column in product table

Revision ID: df5e1453777b
Revises: 5b9ab255271c
Create Date: 2026-09-08 15:21:07.667075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5e1453777b'
down_revision: Union[str, Sequence[str], None] = '5b9ab255271c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
